version: "3.8"
services:
  nginx:
    image: nginx
    container_name: AzetioNginx
    network: host
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled