version: "3.8"
services:
  nginx:
    image: nginx
    container_name: AzetioNginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/ssl:/etc/ssl
      - ./files:/www/data
      - ./logs:/var/log/nginx
      - ./static-pages:/etc/nginx/html
      - ./bhop-maps/sojourner.me:/www/fastdl
